import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import backgroundImg from '../app/public/bg.jpg';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJs Sample Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Image  src={backgroundImg} 
                alt="Background" 
                layout="fill" 
                objectFit="cover" 
                quality={100}
                className="pointer-events-none -z-10"
                style={{ backgroundRepeat: 'repeat', backgroundImage: `url(${backgroundImg.src})` }}/> 
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
